# Generated by Django 4.2.21 on 2025-07-03 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_rename_category_categories_alter_categories_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
